
1. Total revenue per month
Monthly Revenue Trend (Core Analysis)

SELECT 
  FORMAT_DATE('%Y-%m', o.order_date) AS month,
  SUM(oi.quantity * p.price) AS revenue
FROM order_items oi
JOIN products p 
  ON oi.product_id = p.product_id
JOIN orders o 
  ON oi.order_id = o.order_id
GROUP BY month
ORDER BY month;

2. How many customers return after their first purchase? 
Customer Retention (Repeat vs One-Time)

SELECT 
  customer_type,
  COUNT(*) AS num_customers
FROM (
  SELECT 
    o.customer_id,
    COUNT(o.order_id) AS total_orders,
    CASE 
      WHEN COUNT(o.order_id) = 1 THEN 'One-Time'
      ELSE 'Repeat'
    END AS customer_type
  FROM orders o
  GROUP BY o.customer_id
)
GROUP BY customer_type;

3. Who are the highest-value customers?
Top Customers by Total Spending

SELECT 
  o.customer_id,
  SUM(oi.quantity * p.price) AS total_spent,
  RANK() OVER (ORDER BY SUM(oi.quantity * p.price) DESC) AS customer_rank
FROM orders o
JOIN order_items oi 
  ON o.order_id = oi.order_id
JOIN products p 
  ON oi.product_id = p.product_id
GROUP BY o.customer_id
ORDER BY total_spent DESC;

4. Total revenue generated by each customer over time
Customer Lifetime Value (CLV)

SELECT 
  o.customer_id,
  COUNT(DISTINCT o.order_id) AS total_orders,
  SUM(oi.quantity * p.price) AS total_revenue,
  ROUND(SUM(oi.quantity * p.price) / COUNT(DISTINCT o.order_id), 2) AS avg_order_value
FROM orders o
JOIN order_items oi 
  ON o.order_id = oi.order_id
JOIN products p 
  ON oi.product_id = p.product_id
GROUP BY o.customer_id
ORDER BY total_revenue DESC;

5. Which products generate the most revenue?
Revenue by Product

SELECT 
  p.product_name,
  SUM(oi.quantity * p.price) AS total_revenue
FROM order_items oi
JOIN products p 
  ON oi.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_revenue DESC;
